spring:
  datasource:
    url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_PORT:${OPENSHIFT_POSTGRESQL_DB_HOST}}/mow
    username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
    password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
spring.jpa:
  hibernate.ddl-auto: create-drop
#logging.level:
#  org.hibernate.tool.hbm2ddl: DEBUG
#  org.hibernate.SQL: DEBUG
#  org.hibernate.type: TRACE