spring:
  datasource:
    url: postgresql://postgresql:5432/mow
    username: ${POSTGRESQL_DB_USERNAME}
    password: ${POSTGRESQL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
spring.jpa:
  hibernate.ddl-auto: create-drop
#logging.level:
#  org.hibernate.tool.hbm2ddl: DEBUG
#  org.hibernate.SQL: DEBUG
#  org.hibernate.type: TRACE